apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: weather
  name: weather
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
      - name: weather
        image: us-south1-docker.pkg.dev/homelab-388417/homelab/weather:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: state
          readOnly: true
          mountPath: /usr/src/weather/state
      volumes:
      - name: state
        emptyDir: {}
      imagePullSecrets:
      - name: regcred
